### ISSUE TITLE
This addItemCommand seems that is missing information about the item.. or the itemType should be inside the item object 🤔

### ISSUE THREAD

**Issue by karinakuroda** [vigidio/zelda-breath-of-the-wild#7]
This addItemCommand seems that is missing information about the item.. or the itemType should be inside the item object 🤔

_Originally posted by @karinakuroda in https://github.com/vigidio/zelda-breath-of-the-wild/pull/6_

**Comment by vigidio** [comment]
ItemId and ItemType are the composite key of the object
